import React from "react";

import Head from "next/head";
import MainMenu from "@/components/UI/Menus/MainMenu";
import { NextPageContext } from "next";
import type { ReactElement } from "react";
import type { NextPageWithLayout } from "@/pages/_app";
import RootLayout from "@/components/layout/RootLayout";
import MenuLayout from "@/components/layout/MenuLayout";
const Play: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Next-Chess | Main Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>PUZZLEAS</div>
    </>
  );
};

Play.getLayout = function getLayout(page: ReactElement) {
  return (
    <RootLayout>
      <MenuLayout>{page}</MenuLayout>
    </RootLayout>
  );
};

export async function getServerSideProps(context: NextPageContext) {
  const req = context.req;
  const res = context.res;
  if (!res) return { props: {} };
  if (!req?.user) {
    res.setHeader("location", "/login");
    res.statusCode = 302;
    res.end();
    return { props: {} };
  }
  console.log(req?.user);
  return { props: { user: req?.user } };
}

export default Play;
