import React from "react";
import { NextPage, NextPageContext } from "next";
import NonSSRWrapper from "@/components/NonSSRWrapper";
import PuzzleSolver from "@/components/puzzle/ZenMode";
import Head from "next/head";
const SolvePuzzles: NextPage = () => {
  return (
    <>
      <Head>
        <title>Solve Puzzles | Next-Chess</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen w-screen justify-center items-center flex bg-[#181818]">
        <main className="flex justify-center items-center w-full h-full">
          <div className="md:h-full w-full w-full flex justify-center items-center  ">
            <NonSSRWrapper>
              <PuzzleSolver />
            </NonSSRWrapper>
          </div>
        </main>
      </div>
    </>
  );
};

export default SolvePuzzles;
