import { UserContext } from "@/context/user";
import Head from "next/head";
import Image from "next/image";
import Game from "@/components/GameLocal";
import { useEffect, useState, useContext } from "react";
import { SocketContext } from "../context/socket";
import styles from "../styles/Home.module.scss";
import Board from "@/components/Board";
import { Color } from "@/util/chess";
import NonSSRWrapper from "@/components/NonSSRWrapper";
import ButtonSocial from "@/components/UI/ButtonSocial";
import Link from "next/link";
import { useRouter } from "next/router";
export default function Home() {
  const [connected, setConnected] = useState(false);
  const socket = useContext(SocketContext);
  const user = useContext(UserContext);
  useEffect(() => {
    socket.on("connect", () => {
      setConnected(socket.connected);
    });
    setConnected(socket.connected);
    return () => {
      socket.off("connect");
    };
  }, []);
  const router = useRouter();
  return (
    <div
      style={{
        backgroundImage: `url("/assets/background.png")`,
        backgroundRepeat: "no-repeat",
        backgroundSize: "cover",
        overflowX: "hidden",
        backgroundPosition: "bottom 0 left 0",
      }}
      className="flex w-screen h-screen justify-center items-center "
    >
      <div className="h-full w-full justify-center items-center flex bg-black/[0.2]">
        <Head>
          <title>Next-Chess</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="flex container justify-center items-center w-full h-full">
          <div className="h-[80%] max-w-[120vh] w-full flex justify-center items-center bg-[#1f1f1f] rounded-lg grid grid-cols-5 shadow-lg">
            <div className="flex flex-col   rounded-l-md col-span-5 lg:col-span-3 h-full w-full justify-center items-center px-20 ">
              <h1 className="text-6xl text-white my-4">Next-Chess</h1>
              <h3 className="text-white">
                Fully featured online Chess GUI made with Next.js and TypeScript
              </h3>
            </div>
            <div className="w-full col-span-5 lg:hidden mt-6 ">
              <div className="border-t border-white/[0.5] w-[80%] mx-auto" />
            </div>
            <div className="flex flex-col  max-w-[500px] items-center justify-center px-4 lg:px-10 xl:px-20 col-span-5 lg:col-span-2 h-[80%] lg:border-l border-white/[0.5] w-full my-4 mx-auto">
              <h2 className="text-2xl text-white my-12">Sign In to Continue</h2>
              <ButtonSocial variant="google" href="/auth/google" />

              <ButtonSocial variant="facebook" href="/auth/facebook" />

              <p className="my-6 text-white">or</p>
              <button className="text-white bg-neutral-600 hover:bg-neutral-700 text-lg py-4 my-6 rounded-md w-full">
                Continue as Guest
              </button>
              <button
                onClick={() => {
                  fetch("/auth/logout", {
                    method: "GET",
                  });
                }}
              >
                Logout
              </button>
            </div>
          </div>
        </main>
      </div>
    </div>
  );
}
